language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - python: "3.5"
      env: TOXENV=oldbs4
    - name: flake8
      env: TOXENV=flake8
      before_script:
      after_success:
  allow_failures:
    - name: flake8
      env: TOXENV=flake8
# command to install dependencies
addons:
  apt:
    packages:
      - clamav-daemon
install:
  - pip install tox-travis coveralls
before_script:
  # we need to download the clamav signature database before the daemon will run
  - sudo service clamav-freshclam stop
  - sudo freshclam
  - sudo service clamav-daemon restart
  - sudo service clamav-daemon status
  - while ! test -S /var/run/clamav/clamd.ctl; do printf "."; sleep 1; done
# command to run tests
script:
  - tox
# do not send emails of broken builds
notifications:
  email: false
after_script:
  - coveralls
cache:
  pip: true
  directories:
    - /var/lib/clamav/
